export const SET_LOADING = 'SET_LOADING' 
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS' 
export const FETCH_ERROR = 'FETCH_ERROR' 

export const SET_CURRENT_PAGE= 'SET_CURRENT_PAGE' 
export const SET_TOTAL_COUNT= 'SET_TOTAL_COUNT' 

export const FETCH_ITEM_BY_ID_SUCCESS = 'FETCH_ITEM_BY_ID_SUCCESS' 

export const ADD_ITEM_TO_BASKET = 'ADD_ITEM_TO_BASKET' 

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SET_CHECKED_LIST = 'SET_CHECKED_LIST'




