# Generated by Django 2.1.5 on 2020-06-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=100)),
                ('memory', models.CharField(max_length=100)),
            ],
        ),
    ]
